default: &default
  adapter: postgresql
  host: localhost

development:
  <<: *default
  database: campaigner_db_development

test: &test
  <<: *default
  database: campaigner_db_test
  min_messages: warning

production:
  <<: *default
  database: campaigner_db_development
