default: &default
  adapter: postgresql
  host: localhost
  username: <%= ENV["POSTGRES_USERNAME"] || "rails_app" %>

development:
  <<: *default
  database: campaigner_db_development

test: &test
  <<: *default
  database: campaigner_db_test
  min_messages: warning

production:
  <<: *default
  database: campaigner_db_development
