# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af81467011379b0aa09f65fa7ae060ae8149d67d175f4350b82afa045ec429e6ee3d0791e01f0b9ef7a1e20bfb6a5dc681ba9534acbb492dfac00d26791cb135

test:
  secret_key_base: ecdf99e758107ef9a24fffa617ed94e58fe13a8eeabadec4c463b3d891a4c1df2f5de92d2464051bc787fd5da74488004d2456705054f6b1ad1a2c431052d1c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
